name: CI
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      PROJECT_PATH: /go/src/github.com/packagrio/bumpr
    strategy:
      matrix:
        package_type: ['chef', 'golang', 'node', 'python', 'ruby']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Test Binaries
        uses: docker://golang:1.13
        env:
          GOOS: linux
          GOARCH: amd64
        run: |
          mkdir -p $PROJECT_PATH
          cp -a $GITHUB_WORKSPACE/* $PROJECT_PATH/
          cd $PROJECT_PATH

          go mod vendor
          ./ci/test-build.sh ${{ matrix.package_type }}


      - name: Test
        uses: "docker://packagrio/packagr:latest-${{ matrix.package_type }}"
        env:
          GOOS: linux
          GOARCH: amd64
        run: |
          mkdir -p $PROJECT_PATH
          cp -a $GITHUB_WORKSPACE/* $PROJECT_PATH/
          cd $PROJECT_PATH

          ./ci/test-execute.sh ${{ matrix.package_type }}
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: |
            /coverage/coverage-${{ matrix.package_type }}.txt
  build:
    name: Build
    runs-on: ubuntu-latest
    container: golang:1.13
    env:
      PROJECT_PATH: /go/src/github.com/packagrio/bumpr
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        env:
          GOOS: linux
          GOARCH: amd64
        run: |
          mkdir -p $PROJECT_PATH
          cp -a $GITHUB_WORKSPACE/* $PROJECT_PATH/
          cd $PROJECT_PATH

          go mod vendor

          go test -v -tags "static" $(go list ./... | grep -v /vendor/)

          go build -ldflags "-X main.goos=linux -X main.goarch=amd64" -o packagr-bumpr-linux-amd64 -tags "static" cmd/bumpr/bumpr.go

          chmod +x packagr-bumpr-linux-amd64
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: |
            ${{ env.PROJECT_PATH }}/packagr-bumpr-linux-amd64
