name: Release
# This workflow is triggered manually
on:
  workflow_dispatch:
    versionBumpType:
      description: 'Version Bump Type (major, minor, patch)'
      required: true
      default: 'patch'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: golang:1.13
    env:
      PROJECT_PATH: /go/src/github.com/packagrio/bumpr
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bump version
        uses: packagrio/action-bumpr-go@v0.0.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        env:
          GOOS: linux
          GOARCH: amd64
        run: |
          mkdir -p $PROJECT_PATH
          cp -a $GITHUB_WORKSPACE/* $PROJECT_PATH/
          cd $PROJECT_PATH

          go mod vendor

          go test -v -tags "static" $(go list ./... | grep -v /vendor/)

          go build -ldflags "-X main.goos=linux -X main.goarch=amd64" -o packagr-bumpr-linux-amd64 -tags "static" cmd/bumpr/bumpr.go

          chmod +x packagr-bumpr-linux-amd64
          ./packagr-bumpr-linux-amd64 --help

